"""create devices table

Revision ID: 6de152f39832
Revises: 4999aa4847a4
Create Date: 2025-04-09 11:12:36.042052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de152f39832'
down_revision: Union[str, None] = '4999aa4847a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('mgmt_ipv4', sa.String(length=16), nullable=True),
    sa.Column('snmp_version', sa.Integer(), nullable=True),
    sa.Column('snmp_community', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_mgmt_ipv4'), 'devices', ['mgmt_ipv4'], unique=True)
    op.create_index(op.f('ix_devices_snmp_community'), 'devices', ['snmp_community'], unique=False)
    op.create_index(op.f('ix_devices_snmp_version'), 'devices', ['snmp_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_snmp_version'), table_name='devices')
    op.drop_index(op.f('ix_devices_snmp_community'), table_name='devices')
    op.drop_index(op.f('ix_devices_mgmt_ipv4'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
